services:
  certbot:
    image: certbot/dns-ovh
    container_name: certbot-ovh
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
      - "./lib:/var/lib/letsencrypt"
      - "./.ovhsecrets:/secrets"
    restart: "no"
